import './globals.css';

import type { Metadata } from 'next';
import { ntSomic, ntSomicVariable } from './fonts';

export const metadata: Metadata = {
  title: 'IDGIE.Prod',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body className={`${ntSomic.variable} ${ntSomicVariable.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
